# This is a basic workflow to help you get started with Actions

name: CateSeriesParse

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  pull_request:
    branches: [ main ]
  watch:
    type: [started]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: 'Delete files'
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git pull --ff-only https://${{ secrets.PAT }}@github.com/lswlover2579/pytools.git
          git rm Series.m3u
          
      # Runs a set of commands using the runners shell
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
        
      - name: 'run 【VideoParse】' 
        run: python3 CateSeries.py

      - name: 'Commit files'
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git pull --ff-only https://${{ secrets.PAT }}@github.com/lswlover2579/pytools.git
          git add .
          git status
          git commit -m "PUSH TO Add changes" -a
          git push https://${{ secrets.PAT }}@github.com/lswlover2579/pytools.git
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.head_ref }}
